# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'grapho_trac'},
  'syms': {'grapho_trac.core': {'grapho_trac.core.foo': ('core.html#foo', 'grapho_trac/core.py')}}}
